### ISSUE TITLE
Images no longer displayed after killing/updating the app

### ISSUE THREAD

**Issue by Nivl** [square/picasso#632]
When I install my app on my device, everything works perfectly. But when I update it (like using the "run" button from Android Studio), or just kill it (by swiping it from my "Recent apps"), the images are no longer displayed.

My code:

````java
Picasso picasso = Picasso.with(mContext);
picasso.setLoggingEnabled(true);
picasso.load(url).into(viewHolder.mainPicture, new Callback() {
    @Override
    public void onSuccess() {
        Log.i(TAG, "PICASSO OK");
    }

    @Override
    public void onError() {
        Log.i(TAG, "PICASSO KO");
    }
});
````

Logs
````
08-27 16:22:41.266      654-654/io.shace.app D/Picasso﹕ Main        created      [R2] Request{http://192.168.0.5:9000/assets/medias/14ce899e-7021-44ef-b44d-bbab5307fa0f.jpg}
08-27 16:22:41.266      654-746/io.shace.app D/Picasso﹕ Dispatcher  enqueued     [R2]+2ms
08-27 16:22:41.276      654-762/io.shace.app D/Picasso﹕ Hunter      executing    [R2]+2ms
08-27 16:22:41.856      654-746/io.shace.app D/Picasso﹕ Dispatcher  retrying     [R2]+586ms
08-27 16:22:41.856      654-748/io.shace.app D/Picasso﹕ Hunter      executing    [R2]+587ms
08-27 16:22:42.576      654-746/io.shace.app D/Picasso﹕ Dispatcher  retrying     [R2]+1307ms
08-27 16:22:42.576      654-749/io.shace.app D/Picasso﹕ Hunter      executing    [R2]+1308ms
08-27 16:22:42.596      654-746/io.shace.app D/Picasso﹕ Dispatcher  batched      [R2]+1326ms for error
08-27 16:22:42.796      654-654/io.shace.app I/EventAdapter﹕ PICASSO KO
08-27 16:22:42.796      654-746/io.shace.app D/Picasso﹕ Dispatcher  delivered    [R2]+1528ms
08-27 16:22:42.796      654-654/io.shace.app D/Picasso﹕ Main        errored      [R2]+1528ms
````

Looks like a cache issue to me. The URL is obviously working (locally) since it's working when I uninstall/reinstall the app. The image is not huge (58KB). It's also the only image I'm trying to load so it's probably not a cache size issue.

The code is inside getView() on a custom Adapter.

**Comment by cnordvik** [comment]
@dnkoutso I recompiled our app with the latest snapshot "picasso-2.4.1-20141231.132545-8.jar" but the user with the issues still experienced the same behavior with images not loading and loads fine with Picasso 2.1.1. Anything I can do to help investigate the issue? Not very easy to troubleshoot since it works fine for 99% of the users including me.

**Comment by dnkoutso** [comment]
Its not yet fixed in 2.5 yet.

**Comment by ricky-hufei** [comment]
@dnkoutso does Picasso support max-age from the HTTP header? I mean, automatically expire and evict the image from cache after "max-age" is reached. I read the whole LruCache.java file and didn't see anything specially done to track the expiration of specific image. Just want double check with you about that. Thanks.

**Comment by f2prateek** [comment]
@ricky-hufei The HTTP caching is implemented by the networking client, not Picasso.

**Comment by dnkoutso** [comment]
What version of okhttp are you guys using?

**Comment by dnkoutso** [comment]
I need a case where i can reproduce this. We have an idea of what the problem is but without reproducing this its hard to know it works.

Can someone who can reproduce build and try `dimitris/content-lenght` (branch has a typo)?

**Comment by perlmonk** [comment]
I encouraged "Received response with 0 content-length header." before. I don't know if is related to 'If-Modified-Since' header and 304 status. I wrote a customize a downloader to solve this.

Heres the real http download method. The result contains response byte data, we insert a cache between load() and this.

```java
    private Result getUrlManualDealRedirect(String url, String headerIfModifideSince) throws IOException {
		boolean tryNext = false;
		
		Result result;
		do {
			CurlHttp curlHttp = CurlHttp.newInstance();

			// Important, we care redirect(301 and 302)
			curlHttp.setFollowLocation(false);
			if (headerIfModifideSince != null) {
				curlHttp.addHeader("If-Modified-Since", headerIfModifideSince);
			}
			
			result = curlHttp.getUrl(url).perform();
			
			if (result.getStatus() == 301 || result.getStatus() == 302) {
				String nextUrl = result.getHeader("Location");
				if (url.equals(nextUrl)) {
					throw new IOException("redirect loop: url=" + url + ", Location=" + nextUrl);
				}
				if (StringUtils.isBlank(nextUrl)) {
					throw new IOException("redirect response without Location header, url=" + nextUrl);
				}
				url = nextUrl;
				tryNext = true;
			} else {
				tryNext = false;
			}
		} while (tryNext == true);
		
		return result;
	}
```

**Comment by soniccat** [comment]
Can be easily reproduced using these urls:
                "http://commondatastorage.googleapis.com/android-tv/Sample%20videos/Zeitgeist/Zeitgeist%202010_%20Year%20in%20Review/bg.jpg",
                "http://commondatastorage.googleapis.com/android-tv/Sample%20videos/Demo%20Slam/Google%20Demo%20Slam_%2020ft%20Search/bg.jpg",
                "http://commondatastorage.googleapis.com/android-tv/Sample%20videos/April%20Fool's%202013/Introducing%20Gmail%20Blue/bg.jpg",
                "http://commondatastorage.googleapis.com/android-tv/Sample%20videos/April%20Fool's%202013/Introducing%20Google%20Fiber%20to%20the%20Pole/bg.jpg",
                "http://commondatastorage.googleapis.com/android-tv/Sample%20videos/April%20Fool's%202013/Introducing%20Google%20Nose/bg.jpg",

**Comment by Jakevin** [comment]
is fixed now ?

compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-apache:2.3.0'
    compile 'com.squareup.okio:okio:1.3.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.3.0'

the same

**Comment by michaelclarkjr** [comment]
I'm getting similar results with Picasso version 2.5.2. Force Stop and suddenly no image is shown where previously it was showing.

**Comment by ajaykk50** [comment]
I'm facing the same problem now.I am not getting large images into image view from url in Picasso.Any solution for this one.

**Comment by cau-no** [comment]
Using version 2.71828 and this issue still exists.
Loading from gallery with URI: "content://media/external/images/media/..." works with picking images,
stops working after restarting the app.

**Comment by saqibmirza2007** [comment]
Its May-2022 and this issue still exist in v 2.71828. Can somebody reopen this
